######################################################################
# Automatically generated by qmake (2.01a) Tue May 7 14:30:32 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network

# Input
HEADERS += logger.hpp \
           logger_types.hpp \
           settings.hpp \
           wp_utils.hpp \
           wp_utils_types.hpp
SOURCES += application.cpp logger.cpp wp_utils.cpp
